# -*- coding: utf-8 -*-
"""HW1-Q1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PPVyQSSOIAk0nXu8Y03H4pRlm_yTB_bU
"""

from google.colab import files
uploaded = files.upload()

import io
import pandas as pd
df = pd.read_csv(io.StringIO(uploaded['Dataset.csv'].decode('utf-8')))
df['New'].values

import numpy as np
import matplotlib.pyplot as plt

infections= df['New'].values
x = range(len(infections))
t = np.log(infections)
plt.plot(x, t, 'o', color='black')

def update(x, t, w, b, alpha):
  N = len(x)
  y = np.dot(x,w) + b
  dedw = np.dot(y - t, x)
  dedb = np.sum(y - t)
  w = w - (alpha/float(N)) * dedw 
  b = b - (alpha/float(N)) * dedb 
  return w, b

def cost(x, t, w, b):
  y = np.dot(x, w) + b
  return np.sum((y - t)** 2) / (2 * len(y))

def train(x, t, w, b, alpha, epochs):
  for e in range(epochs):
    w, b = update(x, t, w, b, alpha)
    if e % 10000 == 0:
      print("w: ", w, " b: ", b, " cost: ", cost(x, t, w, b))
  return w, b

w, b = train(x, t, w=0, b=0, alpha=0.0001, epochs=100000)

y = np.dot(x, w) + b
plt.plot(x, y)
plt.plot(x, t, 'o', color='black')

